# ci-template-version: 1.1
name: Helm chart release

on:
  workflow_call:
    inputs:
      charts-dir:
        description: Directory containing Helm charts to release
        type: string
        default: 'charts'
      helm-version:
        description: Helm version to install
        type: string
        default: 'v3.14.0'

jobs:
  release:
    name: chart-releaser
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ inputs.helm-version }}
      - uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ${{ inputs.charts-dir }}
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
