# ci-template-version: 1.1
name: TypeScript build

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'
      working-directory:
        description: Directory containing package.json
        type: string
        default: '.'

jobs:
  build:
    name: npm run build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: luukjuh123/gitops-templates/.github/actions/setup-node@main
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
      - name: Build
        run: npm run build
